import Head from 'next/head'
import LMap from '../components/map'

const Home = () => (
    <>
      <Head>
        <title>Новини</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="with-sidebar">
        <LMap />

        <div className="sidebar" style={{ '--sidebar-size': '30rem' }}>
          News go here...
        </div>
      </div>
    </>
  )

export default Home
