import Head from 'next/head'
import PostsMap from '../components/map'
import PostCard from '../components/post'
import { useData } from '../data'

const Home = () => {
  const { data, error } = useData()
  const postGroups = data || []

  return (
    <>
      <Head>
        <title>Новини</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="with-sidebar">
        <PostsMap data={postGroups.flatMap(p => p.expand())} />

        <ul className="sidebar" style={{ '--sidebar-size': '30rem' }}>
          {postGroups.map(post => (
            <PostCard
              key={post.url}
              data={post}
              tag="li"
            />
          ))}
        </ul>
      </div>
    </>
  )
}

export default Home
