import Head from 'next/head'
import LMap from '../components/map'
import { useData } from '../data'

const Home = () => {
  const { data, error } = useData()
  const posts = data || []

  return (
    <>
      <Head>
        <title>Новини</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="with-sidebar">
        <LMap posts={posts} />

        <ul className="sidebar" style={{ '--sidebar-size': '30rem' }}>
          {posts.map(({ url, title, body, freshness }) => (
            <li key={url}>
              {title} {freshness}
            </li>
          ))}
        </ul>
      </div>
    </>
  )
}

export default Home
