const LOCALE = 'uk-UA'

export const DURATION_SECOND = 1000 // ms
export const DURATION_MINUTE = 60 * DURATION_SECOND
export const DURATION_HOUR = 60 * DURATION_MINUTE
export const DURATION_DAY = 24 * DURATION_HOUR
export const DURATION_WEEK = 7 * DURATION_DAY
export const DURATION_MONTH = 30 * DURATION_DAY
export const DURATION_YEAR = 365 * DURATION_DAY
